import { useEffect, useRef, useState } from 'react'
import PeerAvatar from '../PeerAvatar'
import { HELP_TYPES, INDUSTRIES, normalizeIndustry } from '../../data/requestOptions'
import { useAuth } from '../../context/AuthContext'
import { buddyRpc } from '../../lib/buddy/api'
import { matchaCta } from '../../lib/matchaCta'

export const DEMO_BUDDIES = [
 {id:'sample-upper-finance',help_types:['Coffee Chat','Advice'],career_focus:['Finance'],common_help:['Coffee Chat','Advice'],common_focus:['Finance']},
 {id:'sample-upper-consulting',help_types:['Resume Review','Advice'],career_focus:['Consulting'],common_help:['Advice'],common_focus:[]},
]
export function RecommendationCards({items,loading,busy,onRefresh,onAct,notice,error,children}) {
 return <section className="br-section" aria-label="Recommended upper-year students"><header><h2>People you should meet</h2><button type="button" disabled={loading||busy} onClick={onRefresh}>Refresh</button></header><p className="br-intro">Upper-year buddies who may be able to help with your post.</p>{children}
 {notice&&<p className="bc-notice" role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}
 {loading?<p role="status">Finding relevant upper-year buddies…</p>:items.length?<div className="br-list">{items.map(item=><article key={item.id} className="br-card"><PeerAvatar name="Anonymous upper-year student" seed={item.id} size={44}/><div className="br-content"><h3>Anonymous upper-year student</h3><span className="br-fit">{item.common_help.length?'Can help with your ask':'Shared career focus'}</span><p>{item.common_help.length?`Can help with ${item.common_help.join(' · ')}.`:''} {item.common_focus.length?`Shared focus on ${item.common_focus.join(' · ')}.`:''}</p><details><summary>View anonymous profile</summary><p><strong>Happy to help with</strong><br/>{item.help_types.join(' · ')}</p>{item.career_focus.length>0&&<p><strong>Career focus</strong><br/>{item.career_focus.join(' · ')}</p>}</details></div><div className="br-actions"><button type="button" style={matchaCta} disabled={busy||item.status==='interested'} onClick={()=>onAct(item,'interested')}>{item.status==='interested'?'Interest sent':'Interested'}</button><button type="button" disabled={busy} onClick={()=>onAct(item,'skipped')}>{item.status==='interested'?'Withdraw interest':'Skip'}</button></div></article>)}</div>:!error&&<p className="br-empty">No new recommendations right now. We’ll show participating buddies when their help overlaps with your post.</p>}
 <p className="br-privacy">Interested shares your post with this buddy as a request to connect. They choose whether to invite you. Their name stays private until you accept their invitation. Your post keeps its chosen visibility.</p></section>
}
export default function BuddyRecommendations({program,posts,version=0}) {
 const [postId,setPostId]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0)
 const lock=useRef(false)
 const activePosts=posts.filter(p=>p.owner==='me'&&(!p.expiresAt||new Date(p.expiresAt)>new Date()))
 const selected=activePosts.some(p=>p.id===postId)?postId:activePosts[0]?.id
 useEffect(()=>{let live=true;setNotice('');setError('');setItems([]);if(!selected)return;setLoading(true);buddyRpc('buddy_recommendations',{p_program:program,p_post:selected}).then(data=>{if(live)setItems(data.items||[])}).catch(()=>{if(live)setError('Recommendations are not available yet. You can still use your posts above.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[program,selected,refresh,version])
 async function act(item,status){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await buddyRpc('buddy_recommendation_act',{p_post:selected,p_card:item.id,p_status:status});setItems(v=>status==='skipped'?v.filter(x=>x.id!==item.id):v.map(x=>x.id===item.id?{...x,status}:x));setNotice(status==='interested'?'Interest sent. This upper-year buddy can now find your post and choose whether to invite you.':item.status==='interested'?'Interest withdrawn.':'Skipped. This suggestion will stay hidden for this post.')}catch(e){setError(e.message)}finally{setBusy(false);lock.current=false}}
 if(!selected)return <section className="br-section"><h2>People you should meet</h2><p>Publish your first post to see relevant anonymous upper-year buddies.</p></section>
 return <RecommendationCards items={items} loading={loading} busy={busy} onRefresh={()=>setRefresh(v=>v+1)} onAct={act} notice={notice} error={error}>{activePosts.length>1&&<label className="br-post-select">Recommendations for<select value={selected} disabled={busy} onChange={e=>setPostId(e.target.value)}>{activePosts.map(p=><option key={p.id} value={p.id}>{p.needs.slice(0,75)}</option>)}</select></label>}</RecommendationCards>
}
export function UpperBuddyProfile({program,onInterestPosts}) {
 const {profile}=useAuth()
 const [card,setCard]=useState({help_types:[],career_focus:[],discoverable:false}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[error,setError]=useState(''),[reload,setReload]=useState(0)
 const dirty=useRef(false),lock=useRef(false)
 useEffect(()=>{let live=true;setLoading(true);buddyRpc('buddy_recommendations',{p_program:program}).then(data=>{if(!live)return;onInterestPosts(data.incoming_post_ids||[]);if(!dirty.current)setCard(data.profile||{help_types:(profile?.can_help_with||[]).filter(x=>HELP_TYPES.includes(x)).slice(0,3),career_focus:[...new Set((profile?.industry_interests||[]).map(normalizeIndustry))].filter(x=>INDUSTRIES.includes(x)).slice(0,2),discoverable:false});setError('')}).catch(()=>{if(live)setError('Anonymous recommendations are not available yet. Your post browsing still works.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[program,reload,onInterestPosts])
 function toggle(key,value,max){dirty.current=true;setCard(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):c[key].length<max?[...c[key],value]:c[key]}))}
 async function save(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await buddyRpc('buddy_upper_card_save',{p_program:program,p_help:card.help_types,p_focus:card.career_focus,p_discoverable:card.discoverable});dirty.current=false;setNotice(card.discoverable?'Your anonymous buddy profile is available for recommendations.':'Your buddy profile is hidden from recommendations.');setReload(v=>v+1)}catch(e){setError(e.message)}finally{setBusy(false);lock.current=false}}
 return <details className="br-profile"><summary>Edit buddy profile</summary><p>Choose what first-year students may see. Your name, photo, employer and contact details are not included.</p>{loading?<p>Loading…</p>:<form onSubmit={save}><fieldset disabled={busy}><legend>Happy to help with · up to 3</legend><div className="br-chips">{HELP_TYPES.map(x=><button type="button" key={x} aria-pressed={card.help_types.includes(x)} onClick={()=>toggle('help_types',x,3)}>{x}</button>)}</div></fieldset><fieldset disabled={busy}><legend>Career focus · up to 2</legend><div className="br-chips">{INDUSTRIES.map(x=><button type="button" key={x} aria-pressed={card.career_focus.includes(x)} onClick={()=>toggle('career_focus',x,2)}>{x}</button>)}</div></fieldset><label className="br-consent"><input type="checkbox" disabled={busy} checked={card.discoverable} onChange={e=>{dirty.current=true;setCard(c=>({...c,discoverable:e.target.checked}))}}/> Recommend my anonymous buddy profile to first-year students in this program.</label><button className="bc-button" type="submit" disabled={busy||(card.discoverable&&!card.help_types.length)} style={matchaCta}>Save profile</button></form>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}<button className="bc-button" type="button" disabled={busy||loading} onClick={()=>setReload(v=>v+1)}>Refresh interests</button></details>
}
