// @vitest-environment jsdom
import React from 'react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
const api = vi.hoisted(() => ({ generate: vi.fn(), fetch: vi.fn(), save: vi.fn(), mutual: vi.fn(), incoming: vi.fn(), respond: vi.fn() }))
vi.mock('../../lib/smartMatch', () => ({ generateSmartMatches: api.generate, fetchVisibleNudges: api.fetch, setNudgeStatus: api.save, checkMutualMatch: api.mutual, fetchIncomingInterests: api.incoming, respondToInterest: api.respond }))
vi.mock('../../lib/analytics', () => ({ track: vi.fn() }))
import SmartMatchSection from '../SmartMatchSection'
const row = { id: 'n1', candidate_id: 'peer', score: 62, reason: 'Shared focus on Finance', status: 'pending' }
beforeEach(() => {
  vi.resetAllMocks()
  api.fetch.mockResolvedValue({ nudges: [row], error: null })
  api.generate.mockResolvedValue({ error: null })
  api.save.mockResolvedValue({ error: null })
  api.mutual.mockResolvedValue({ matched: false })
  api.incoming.mockResolvedValue({ incoming: [], error: null })
})
afterEach(cleanup)
it('keeps the card after one-sided interest and explains the next step', async () => {
  render(<SmartMatchSection />)
  fireEvent.click(await screen.findByRole('button', { name: 'Interested' }))
  expect(await screen.findByText('Interest saved')).toBeTruthy()
  expect(screen.getByRole('article')).toBeTruthy()
  expect(screen.getByText(/We let them know/)).toBeTruthy()
  expect(screen.queryByRole('button', { name: 'Interested' })).toBeNull()
  expect(screen.queryByText(/62%/)).toBeNull()
})
it('restores saved interest when returning and after Refresh', async () => {
  api.fetch.mockResolvedValue({ nudges: [{ ...row, status: 'interested' }], error: null })
  const view = render(<SmartMatchSection />)
  await screen.findByText('Interest saved')
  await waitFor(() => expect(screen.getByRole('button', { name: 'Refresh' }).disabled).toBe(false))
  fireEvent.click(screen.getByRole('button', { name: 'Refresh' }))
  await waitFor(() => expect(screen.getByRole('button', { name: 'Refresh' }).disabled).toBe(false))
  expect(screen.getByText('Interest saved')).toBeTruthy()
  view.unmount()
  render(<SmartMatchSection />)
  expect(await screen.findByText('Interest saved')).toBeTruthy()
  expect(api.save).not.toHaveBeenCalled()
})
it('provides a Matches action after mutual interest without revealing identity', async () => {
  api.mutual.mockResolvedValue({ matched: true, matchId: 'm1' })
  const open = vi.fn()
  render(<SmartMatchSection onOpenMatches={open} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Interested' }))
  fireEvent.click(await screen.findByRole('button', { name: 'View Matches' }))
  expect(open).toHaveBeenCalledTimes(1)
  expect(screen.getByText('Anonymous peer')).toBeTruthy()
})
it('restores matched status from storage', async () => {
  api.fetch.mockResolvedValue({ nudges: [{ ...row, status: 'matched' }], error: null })
  render(<SmartMatchSection onOpenMatches={vi.fn()} />)
  expect(await screen.findByRole('button', { name: 'View Matches' })).toBeTruthy()
  expect(api.save).not.toHaveBeenCalled()
})
it.each([false, true])('keeps the suggestion retryable if saving fails (throw=%s)', async throws => {
  if (throws) api.save.mockRejectedValue(new Error('Offline'))
  else api.save.mockResolvedValue({ error: new Error('No row') })
  render(<SmartMatchSection />)
  fireEvent.click(await screen.findByRole('button', { name: 'Interested' }))
  expect((await screen.findByRole('alert')).textContent).toContain('Could not save your choice')
  expect(screen.getByRole('button', { name: 'Interested' }).disabled).toBe(false)
  expect(api.mutual).not.toHaveBeenCalled()
})
it('preserves successful interest when connection lookup fails', async () => {
  api.mutual.mockRejectedValue(new Error('Offline'))
  render(<SmartMatchSection />)
  fireEvent.click(await screen.findByRole('button', { name: 'Interested' }))
  await screen.findByText(/We could not check for a connection/)
  expect(screen.getByText('Interest saved')).toBeTruthy()
  expect(screen.queryByRole('alert')).toBeNull()
})
it('locks Refresh and repeated actions until saving completes', async () => {
  let resolve
  api.save.mockReturnValue(new Promise(r => { resolve = r }))
  render(<SmartMatchSection />)
  const interested = await screen.findByRole('button', { name: 'Interested' })
  fireEvent.click(interested)
  fireEvent.click(interested)
  const refresh = screen.getByRole('button', { name: 'Refresh' })
  expect(refresh.disabled).toBe(true)
  fireEvent.click(refresh)
  expect(api.generate).not.toHaveBeenCalled()
  expect(api.save).toHaveBeenCalledTimes(1)
  await act(async () => resolve({ error: null }))
  expect(screen.getByText('Interest saved')).toBeTruthy()
})
it('only removes a skipped suggestion after the write succeeds', async () => {
  render(<SmartMatchSection />)
  fireEvent.click(await screen.findByRole('button', { name: 'Skip' }))
  await screen.findByText('Suggestion skipped.')
  expect(screen.queryByRole('article')).toBeNull()
})
it('keeps saved interests visible when generation fails', async () => {
  api.fetch.mockResolvedValue({ nudges: [{ ...row, status: 'interested' }], error: null })
  api.generate.mockRejectedValue(new Error('Offline'))
  render(<SmartMatchSection />)
  await screen.findByRole('alert')
  expect(screen.getByText('Interest saved')).toBeTruthy()
})
it('shows the first name of a member who chose a Public profile', async () => {
  api.fetch.mockResolvedValue({ nudges: [{ ...row, publicName: 'Sarah' }], error: null })
  render(<SmartMatchSection />)
  expect(await screen.findByText('Sarah')).toBeTruthy()
  expect(screen.queryByText('Anonymous peer')).toBeNull()
})
it('lets a private sender connect without ever seeing who they are, and Not now stays silent', async () => {
  api.fetch.mockResolvedValue({ nudges: [row], error: null })
  api.incoming.mockResolvedValue({ incoming: [{ nudge_id: 'in1', public_id: null, public_name: null, my_pending_nudge_id: 'n1' }], error: null })
  api.respond.mockResolvedValue({ matched: true, matchId: 'm9', error: null })
  const open = vi.fn()
  render(<SmartMatchSection onOpenMatches={open} />)
  expect(await screen.findByText('Someone in your community')).toBeTruthy()
  // My own suggestion for the same person is folded into this card.
  expect(screen.getAllByRole('article')).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', { name: 'Interested' }))
  expect(await screen.findByText('You are both interested')).toBeTruthy()
  expect(api.respond).toHaveBeenCalledWith('in1', true)
  fireEvent.click(screen.getByRole('button', { name: 'View Matches' }))
  expect(open).toHaveBeenCalled()
})
it('names a Public sender and removes the card quietly on Not now', async () => {
  api.incoming.mockResolvedValue({ incoming: [{ nudge_id: 'in2', public_id: 'pub', public_name: 'Sarah' }], error: null })
  api.respond.mockResolvedValue({ matched: false, matchId: null, error: null })
  render(<SmartMatchSection />)
  expect(await screen.findByText('Sarah')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Not now' }))
  expect(await screen.findByText('Okay. They will not be told.')).toBeTruthy()
  expect(screen.queryByText('Sarah')).toBeNull()
  expect(api.respond).toHaveBeenCalledWith('in2', false)
})
